### PR TITLE
Pass originalEvent to FISISH_EVENT

### PR DESCRIPTION
**Pull request by hoetmaaiers**
I need to know if shiftKey is pressed when the lasso event is used. This addition passes the original event to the `FISISH_EVENT`. This is analogue to the LeafletMouseEvent`

Maybe some documentation should be updated?

### CODE REVIEW

**Comment by zakjan** [comment]
Thanks for the PR! Yes please, update the readme with the new event interface.

**Comment by hoetmaaiers** [comment]
Ok, an update coming up.
I was also thinking about exporting the interface `LassoHandlerFinishedEventData`. Currently I have to copy/paste this in my own codebase, but exporting would be nicer?

**Comment by hoetmaaiers** [comment]
Anything else to add before accepting this PR?

**Comment by zakjan** [comment]
Looks good, released as 2.2.7

**Pull request merged**
