### PR TITLE
Grunt build and slightly improved mouse handling

### PR DESCRIPTION
**Pull request by DerGuteWolf**

### CODE REVIEW

**Comment by DerGuteWolf** [comment]
Sorry, this is unsquashed

**Comment by zakjan** [comment]
There is already Webpack for building, no need to add another library.

Can you describe the improvements in mouse handling?

**Comment by DerGuteWolf** [comment]
Well, grunt calls to and webpack, so nothing duplicated just additional. Grunt build is helpful as there a lot's of ci pipelines and the like only support grunt.
When you unpress the mouse while lassoing over a leaflet control, the so far achieved lasso selection was left painted but got orphaned and a new lasso selection was started.

**Comment by zakjan** [comment]
I'm curious, which CI supports grunt only?

Anyway, consumers can use the built version as published to npm, no need to call internal plugin build commands. I'm going to reject this.

For mouse interaction, I can't replicate the behavior for native Leaflet controls. Unpressing the mouse on Leaflet zoom control on the demo page works correctly. Do you use any other Leaflet plugin? Maybe it could be a bug in the other plugin. Can you create a new PR for the mouse interaction only, with a gist where it is replicated?

**Comment by DerGuteWolf** [comment]
SAP's Cloud WebIDE and Cloud CI pipeline. But that's ok if you reject this.
Regarding mouse control: https://gist.github.com/DerGuteWolf/d89d2c6818f99dcf0ca39730cfd976b8 and https://rawgit.com/DerGuteWolf/d89d2c6818f99dcf0ca39730cfd976b8/raw/930eecc40c8494e0fc3a85ce28e8e473eb403b2a/index.html . Click on the star, start lasso by mouse down in the map, move to star button, mouse up, mouse down in the map (preferably some other area), move mouse,mouse up, see artifacts remaining.
I have also made a video depicting this, but better try yourself.

**Comment by zakjan** [comment]
I see. I'd say this is a bug in the EasyButton plugin.

**Comment by zakjan** [comment]
Never mind, I fixed it here by using capture flag on event listener. Released as 1.1.1

**Comment by DerGuteWolf** [comment]
Thanks for providing 1.1.1. Unfortunatly this is still not working complete correct.
https://rawgit.com/DerGuteWolf/d89d2c6818f99dcf0ca39730cfd976b8/raw/5cb1faa5934c3c343ca77ad76d8b224dc14c3a63/index.html uses 1.1.1.
click on star, mouse down in map, move to zoom control, mouse up, click on star, mouse down in map, move in map (problems are starting), mouse up in map, move, mouse down in map, move, mouse up in map -> artefact remaining.
So as this happens also with the zoom control, this is definitly not a bug in the EasyButton plugin.

**Comment by zakjan** [comment]
That's because browser thinks it should select text as usual... Try now with 1.1.2, I disabled it on body.

**Comment by DerGuteWolf** [comment]
Unfortunatly you can't do this if there is some other stuff on the web page which needs text selection.  Perhaps it's enough to disable it only on the map's div. You can use getContainer() on the map. Or you disable this only during lassoing? But even in this case you should restore the previous state...

**Comment by zakjan** [comment]
Selection must be disabled on the entire document during lassoing. It is disabled again when mouse is released, it should be fine. Unless some other component steals the event again.

**Comment by DerGuteWolf** [comment]
I would still propose my fix:
```
    onMouseDown(event: LeafletEvent) {
        if (this.polygon) { // lost one mouseup event eg because another map control "stole" it, thus ignore this and continue
            return;
        }
```
Messing arround with something outside the map is certainly not a good idea.  Also if one has set eg `document.body.style.userSelect = 'all';` this will be gone after lassoing.

**Comment by zakjan** [comment]
Ok, I have moved setting user-select to the map container, fortunately it behaves the same for the entire document when mousedown starts in the map container.

About your suggestion to fix mousedown, it introduces a weird new behavior for the user. Mousedown should always start a new lasso selection. For me this would be a bug of anything else that steals mouseup.

**Comment by DerGuteWolf** [comment]
ok, but you should clean up before continue on a onMouseDown, ie do something like this:
```
    onMouseDown(event: LeafletEvent) {
        if (this.polygon) { // lost one mouseup event eg because another map control "stole" it, thus ignore this and continue
            this.map.removeLayer(this.polygon);
        }
```

**Comment by zakjan** [comment]
It is already cleaned up in mouseup. Do you have this problem with a specific other plugin, where we can replicate it?

**Comment by DerGuteWolf** [comment]
Yes, but if the mouseup event is lost, cleaning there does not help. Thus I would propose cleaning up also in mousedown (defensive programming).

**Comment by zakjan** [comment]
Hi @DerGuteWolf, can you check if it works better for you in the new version released today? In the end I have added the check you suggested.

**Comment by DerGuteWolf** [comment]
Sorry, forgot to answer, yes this works great now!

**Comment by zakjan** [comment]
Awesome, thanks :)

**Pull request closed without merging**
